export const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today?",
    gptSearch: "GPT Search",
    signOut: "Sign Out",
    signIn: "Sign In",
    signUp: "Sign Up",
    enterFullName: "Enter your full name",
    emailPlaceholder: "Email or mobile number",
    passwordPlaceholder: "Password",
    rememberMe: "Remember me",
    newToNetflix: "New to NetFlix? ",
    alreadyMember: "Already a member? ",
    signUpNow: "Sign up now.",
    signInNow: "Sign In.",
    play: "Play",
    moreInfo: "More Info",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    gptSearch: "जीपीटी खोज",
    signOut: "साइन आउट",
    signIn: "साइन इन",
    signUp: "साइन अप",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    emailPlaceholder: "ईमेल या मोबाइल नंबर",
    passwordPlaceholder: "पासवर्ड",
    rememberMe: "मुझे याद रखें",
    newToNetflix: "नेटफ्लिक्स पर नए हैं? ",
    alreadyMember: "क्या पहले से ही सदस्य हैं? ",
    signUpNow: "अभी साइन अप करें।",
    signInNow: "साइन इन करें।",
    play: "चलाएं",
    moreInfo: "और जानकारी",
  },
  chinese: {
    search: "搜索",
    gptSearchPlaceholder: "今天你想看什么？",
    gptSearch: "GPT 搜索",
    signOut: "登出",
    signIn: "登录",
    signUp: "注册",
    enterFullName: "输入您的全名",
    emailPlaceholder: "电子邮件或手机号码",
    passwordPlaceholder: "密码",
    rememberMe: "记住我",
    newToNetflix: "刚接触 Netflix？ ",
    alreadyMember: "已经是会员？ ",
    signUpNow: "立即注册。",
    signInNow: "登录。",
    play: "播放",
    moreInfo: "更多信息",
  },
};

export const SUPPORTED_LANGUAGES = [
  { identifier: "en", name: "English" },
  { identifier: "hindi", name: "Hindi" },
  { identifier: "chinese", name: "Chinese" },
];
